name: sliver_calendar
description: Display a calendar view for flutter.
version: 0.2.0
author: David Bennett <pinkfishfrog@gmail.com>
homepage: https://github.com/pinkfish/flutter_calendar

environment:
    sdk: ">=1.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  flutter_native_timezone: ^1.0.2
  timezone: ^0.5.2

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

